name: ml_fastapi
channels:
  - conda-forge
  - defaults
dependencies:  
  - scikit-learn
  - pandas
  - numpy
  - pytest
  - jupyter  
  - jupyterlab
  - fastapi
  - uvicorn
  - logging
  - pickle
  
  
  